### ISSUE TITLE
@:header not sent when route type is `Noise` or `Promise<Noise>`

### ISSUE THREAD

**Issue by emugel** [haxetink/tink_web#114]
`@:get('/test1') @:header("foo", "bar") public function test1() return Noise;`
Server never sends a "foo" header in the response.

`@:get('/test1') @:header("foo", "bar") public function test1() return "OK";` 
Works.

It seems to not work when the route return type is `Noise` or `Promise<Noise>`.

Arguably Noise on a GET method doesn't make sense but it's the same on a DELETE one.

**Comment by kevinresol** [comment]
I think we need to add the handling here: https://github.com/haxetink/tink_web/blob/356369e5bdfd9ac6193b279e5555546ba6d6724f/src/tink/web/macros/Routing.hx#L379-L384
