### ISSUE TITLE
Scheme and the colon

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#119]
So: `{scheme: 'http:'}` works but `{scheme: 'http'}` doesn't.

I guess we should detect that and auto add it.

**Comment by back2dos** [comment]
Uhm, I'm slightly confused. Is it not added [here](https://github.com/haxetink/tink_web/blob/7b02e18e75309000e868252b6335eb75c69a7b7b/src/tink/web/proxy/Remote.hx#L77) or are you referring to something else?

**Comment by kevinresol** [comment]
oops, because I did this:

```haxe
var endpoint:RemoteEndpoint = {
	host: new Host(config.host, config.port),
	scheme: config.scheme,
	path: config.path
		.split('/')
		.filter(v -> v != '')
		.map(Portion.new)
	,
}
`

**Comment by back2dos** [comment]
Totally missed the implicit cast. Should work fine now ;)
