### ISSUE TITLE
Doesn't recognize content-type header with extension

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#13]
`Content-Type: application/json; charset=UTF-8` will fail [here](https://github.com/haxetink/tink_web/blob/3145ae37c2e24135a7c3693205dde9a933884b10/src/tink/web/macros/Routing.hx#L124)

**Comment by kevinresol** [comment]
This https://github.com/haxetink/tink_http/pull/45 should help

**Comment by back2dos** [comment]
I believe this is handled correctly on the fullstack branch. Will check again though.

**Comment by kevinresol** [comment]
Need to write some tests

**Comment by back2dos** [comment]
Works now.
