### ISSUE TITLE
Proxy: Custom headers

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#27]
Again, I'm trying to build remote client against the google api. I need a way to insert my access token to the Authorization header of the request, and I can't find a way to do so.

Fortunately google supports passing the access token through the query parameter, so I can work around it for now. But that may not be the case for other apis.

**Comment by back2dos** [comment]
As far as authorization tokens are concerned, I use something like:

```haxe
class AuthedClient implements Client {
  var actual:Client;
  public function request(req:OutgoingRequest) {
    return actual.request(withAdditionalHeaders(req));
  }
}

//usage example:
new Proxy<Api>(new AuthedClient(new NodeClient()));
```

**Comment by kevinresol** [comment]
neat idea :wink:
