### ISSUE TITLE
Support status code and header in the response

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#34]
... and also for proxy.

**Comment by kevinresol** [comment]
Haven't really deeply dived into it. But this looks like a good reference:
http://square.github.io/retrofit/

It does something like this to allow custom headers:
```java
@GET("user")
Call<User> getUser(@Header("Authorization") String authorization)
```

**Comment by back2dos** [comment]
Oh, cool project :)

That only deals with *request* headers though. Those can be captured as `header` or with `@:params(<name> in header)`. See https://github.com/haxetink/tink_web/blob/4e93e740b2690c27233556729896c6b201654a71/tests/Fake.hx#L47

**Comment by kevinresol** [comment]
What if we introduce typed responses? which has `header` and  `body` = parsed data.

So the api will look like:

```haxe
@:get public function get():Promise<Response<{mydata:String}>>
```

seems not bad for both server and client

**Comment by back2dos** [comment]
Yup, that sounds good :)

**Comment by kevinresol** [comment]
This is implemented, the remaining discussion should go to https://github.com/haxetink/tink_web/issues/40
