### ISSUE TITLE
Example for how to implement sessions?

### ISSUE THREAD

**Issue by FuzzyWuzzie** [haxetink/tink_web#36]
I'm trying to use this instead of writing all my own routing etc, but in true tink fashion the ways things are done are extremely non-obvious to me.

I'm trying to set up a basic authentication scheme (I'll be using JWT, which I have a lot of experience with), so I basically want to parse the `authorization` header and store the data in some User object. This page: https://haxetink.github.io/tink_web/#/advanced/access-control seems like exactly what I need, except however I try to implement it, I always end up with:

```
src/server/routes/Root.hx:10: characters 5-14 : restriction cannot be applied because no session handling is provided
```

I have no idea how to "provide session handling"—I thought I was doing that [here](https://github.com/FuzzyWuzzie/wysh/blob/tink_web/src/server/Server.hx#L63-L65):

```haxe
container.run(function(req) {
    return router.route(Context.authed(req, Session.new)).recover(OutgoingResponse.reportError);
});
```

But that certainly isn't working. Trying to dig through the `tink_web` code, I quickly get bogged down by tink_macro stuff that I'm not at all familiar with, and the `Fake.hx` tests page is useless because it doesn't actually do any of the things talked about in the docs.

So, can anyone hold my hand and show me what to do for this last small step?

Thanks so much!

**Comment by kevinresol** [comment]
Can you show me how you initialized your router?

**Comment by FuzzyWuzzie** [comment]
Thanks!

In main:
```haxe
var container = new TcpContainer(8080);
var router = new Router<Root>(new Root());
Log.info('listening on port 8080!');
container.run(function(req) {
    return router.route(Context.authed(req, Session.new)).recover(OutgoingResponse.reportError);
});
```

Root.hx:
```
package routes;

import tink.http.Response.ResponseHeader;
import tink.http.Response.OutgoingResponse;
import tink.web.routing.*;

class Root {
    public function new() {}

    //@:restrict(true)
    @:sub public function lists() {
        return new Lists();
    }
}
```

**Comment by kevinresol** [comment]
Yeah there is the problem, it should be `new Router<MySession, Root>`

**Comment by kevinresol** [comment]
Check out the complete example here: https://github.com/kevinresol/tink_workshop2017

**Comment by FuzzyWuzzie** [comment]
Great, that solved the issues.

Thanks so much!

**Comment by kevinresol** [comment]
Reopening to remind me fixing the doc

**Comment by kevinresol** [comment]
48e9135cc00f6701a106cc1454dd2a8709795173

**Comment by araneta** [comment]
@hamaluik  do you know jwt library for haxe for php?
thanks

**Comment by kevinresol** [comment]
> @hamaluik do you know jwt library for haxe for php? thanks

https://github.com/kevinresol/jsonwebtoken

**Comment by araneta** [comment]
Thanks Kevin, I'm trying to use jwt using your session on https://github.com/kevinresol/tink_workshop2017
