### ISSUE TITLE
Proxy should return Promise<tink.web.Response> by default

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#41]
Otherwise some meta information (header) will be lost and unrecoverable.

If people need only the data just call `toData()` of the response.

Or:

```haxe
abstract PromisedResponse<T>(Promise<tink.web.Response<T>>) {
  @:to public inline function asData():Promise<T>
    return this.map(function(res) return res.toData());
}

**Comment by back2dos** [comment]
Not sure I like this, because personally I don't care about the header in ~95% of all use cases. I wonder: if you actually want the header, why not update the call signature accordingly?

**Comment by kevinresol** [comment]
alright

**Comment by kevinresol** [comment]
second thought: what if I cannot control the signature (a library)?

**Comment by back2dos** [comment]
Well, technically you can always hijack 3rd party code per `--macro addGlobalMetadata("path.to.TheClass", "@:build(MyHacks.apply())", false)`. I'm not saying you should, but it's always good to know you can ;)

My thinking is that either there's true data in the header (not just the overhead of HTTP), in which case the response type should be`Response`, or not, in which case you want just the payload an the type should reflect that.

I mean, if this is really a thing, then I suppose we could make `Proxy` take 1 or 2 params and then `Proxy<Target, WithHeaders>` would do what you want.
