### ISSUE TITLE
Bool default param must be false

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#42]
```haxe
@:get
public function get(bool = true);
```
will always give bool = false. Because the router plugs in a null when it cannot capture the param in the path. And null is interpreted as false by Stringly.

**Comment by back2dos** [comment]
Can you check if it works correctly with `@:get public function get(?bool = true);`?

**Comment by kevinresol** [comment]
same

**Comment by back2dos** [comment]
Ah, ok, I got it: `((null: tink.Stringly) : Bool)` [always becomes false](https://github.com/haxetink/tink_stringly/blob/master/src/tink/Stringly.hx#L50). 

I think something like this might exhibit the expected behavior (not sure about edge cases on static platforms):

```haxe
  @:to public function toNullBool():Null<Bool>
    return 
      if (this == null) null;
      else switch this.trim().toLowerCase() {
        case 'false', '0', 'no': false;
        default: true;
      }
  @:to public function toBool():Bool
     return toNullBool() == true;
```
