### ISSUE TITLE
[Proxy] Add Content-Length header when possible

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#44]
Some API endpoints chokes without it.

**Comment by back2dos** [comment]
Yeah, this one is a little tricky, because browsers will punch you in the face when you try to do that: https://stackoverflow.com/questions/7210507/ajax-post-error-refused-to-set-unsafe-header-connection

**Comment by kevinresol** [comment]
I am using nodejs to issue the request now. Maybe`#if (!js || nodejs) addContentLength() #end`?

**Comment by kevinresol** [comment]
We got a duplicate issue, let's continue there #52
