### ISSUE TITLE
Strange Typing Error

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#47]
```haxe
interface Api {
  @:post
  public function post(body:{id:String}):Promise<{var id(default, never):String;}>;
}
```
This is throwing me some incompatible accessor error. Something about `never` should be `default`.

What I guess is that somewhere in tink_macro doesn't distinguish the two types. So some parsers/writers are mixed. Maybe somewhere around DirectType.

**Comment by back2dos** [comment]
Ok, this is crazy.

This compiles:

```haxe
var r = new tink.web.routing.Router<Api>(null);
var r = new tink.web.proxy.Remote<Api>(null, null);
```

This doesn't:

```haxe
var r = new tink.web.routing.Router<Api>(null);
var r = new tink.web.proxy.Remote<Api>(null, null);
```

I have a feeling this is gonna be fun ^^

**Comment by benmerckx** [comment]
Those are... the same?

**Comment by kevinresol** [comment]
Current workaround is to add a dummy optional field to `body`

**Comment by back2dos** [comment]
@benmerckx Yeah, sorry fixed that ;)

I somehow suspect that tink_querystring or tink_json get consider the types equal although they shouldn't.

**Comment by back2dos** [comment]
Seems to work now.
