### ISSUE TITLE
@:params(myParam in header) doesn't work

### ISSUE THREAD

**Issue by grosmar** [haxetink/tink_web#53]
there are 3 type of predefined parts of a request accessible through @:params:
body, query, header

The first two works perfectly, but the header doesn't:

example:
`@:params(password in header)`

**Comment by kevinresol** [comment]
how about:

```haxe
  @:get public function headers(header: { accept:String } ) {
    return header.accept;
  }   
```

**Comment by grosmar** [comment]
Do you propose as a workaround or to check if it working in this case?

Btw, I use it from the client side, so there will be no implementation of the interface.

**Comment by kevinresol** [comment]
Just a check. Also you should post the error you got `@:params(password in header)`

**Comment by grosmar** [comment]
No error, it's just ignored

**Comment by kevinresol** [comment]
Hmmm, seems like we have failing test here already: https://github.com/haxetink/tink_web/blob/450fff3/tests/ProxyTest.hx#L50

**Comment by kevinresol** [comment]
I think I have identified the problem, there is no logic to handle header when building the proxy:
https://github.com/haxetink/tink_web/blob/88d922e/src/tink/web/macros/Proxify.hx#L40-L69

But the codebase is a bit complex...
