### ISSUE TITLE
Creating remote fails when a route has an abstract enum param

### ISSUE THREAD

**Issue by gene-pavlovsky** [haxetink/tink_web#60]
Using the latest `pure` branch.
I have this interface defined for an external API (non-`tink_web`) that I want to use:

```
interface ExternalApi {
	@:get('/files.php')
	function files(query:{
		var action:FilesAction;
		var file_id:String;
	}):{result:Bool, message:String};
}

@:enum abstract FilesAction(String) from String to String {
	var New = "new";
	var Delete = "delete";
}
```

When trying to create a remote for it:
`extRemote = new Remote<ExternalApi>(new SecureNodeClient(), new RemoteEndpoint(...));`
The following compile error occurs:
```
C:/usr/local/haxe/haxe_libraries/tink_web/0.0.0/github/f93fd00a895d191e76d4e04de17afb8481fc59b1/src/tink/web/macros/Proxify.hx:22: characters 27-33 : FilesAction should be tink.Stringly
C:/usr/local/haxe/haxe_libraries/tink_web/0.0.0/github/f93fd00a895d191e76d4e04de17afb8481fc59b1/src/tink/web/macros/Proxify.hx:22: characters 27-33 : For function argument 'value'
C:/usr/local/haxe/haxe_libraries/tink_querystring/0.5.0/haxelib/src/tink/querystring/macros/GenBuilder.hx:140: lines 140-151 : Defined in this class
```

P.S. If I use the same abstract enum for my own server `new Router<Root>(root);`, it works.

**Comment by kevinresol** [comment]
you need a `to tink.Stringly` for your abstract

**Comment by gene-pavlovsky** [comment]
Is it considered a proper usage, or a workaround?

**Comment by kevinresol** [comment]
I think it is a workaround.
In fact I think the library should be able to figure out the abstract's underlying type and cast from there automatically.
