### ISSUE TITLE
Proxy's accept header shouldn't be  `*/*` ?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#72]
When using a proxy against an endpoint that has `@:html`, it will get `text/html` response which screw up the client side response parser. I guess the proxy should be able to figure out the correct ACCEPT header from the API?

**Comment by back2dos** [comment]
In theory the proxy should send an `Accept: text/json`.

**Comment by kevinresol** [comment]
Yes, but currently it is `*/*`. I worked around it by adding `.sub({header: [...]})` to the remote endpoint
