### ISSUE TITLE
relative path on php

### ISSUE THREAD

**Issue by francescoagati** [haxetink/tink_web#78]
hi,
when i use tinkweb with php with a page php the is inside a page i get not found.
for example
/a/b/c/index.php?q=/hello/frank

how can i handle /hello/frank with a query parameter inside a subpath?

**Comment by kevinresol** [comment]
Sorry I don't get it...

**Comment by francescoagati** [comment]
i am try to use tink_web on php without url rewrite and inside a subfolder. there is a mode for use tink_web in this conditions?

**Comment by kevinresol** [comment]
You can write a middleware to strip off the path

**Comment by francescoagati** [comment]
ok thanks i will try with a middleware
