### ISSUE TITLE
Option to accept json and/or url-encoded

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#8]
Currently tink_web supports both by default. It would be nice to allow specifying what content type to accept, per route or globally. Then there is no need to generate the unnecessary parser. When a request of an unacceptable content type arrives, simply throw an error or fire a `unacceptableContentType` callback.

**Comment by back2dos** [comment]
Yep. I do plan to have a plugin system for this, so a route should have something like `@:accepts('application/json', 'application/xml', 'application/x-plist', 'text/csv')` and then the parsers would be generated based on that. For csv it would probably demand the body type to be `Array<X>` and what not.
