### ISSUE TITLE
"file extension" on path & @:sub

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#82]
from @nanjizal's issue https://github.com/haxetink/tink_http/issues/106 I did a look at shopify's REST API. I found that it appends a "file extension" (i.e. `.json`) to every API endpoint. Examples:

- `GET /admin/products.json`
- `GET /admin/products/count.json`
- `GET /admin/products/#{product_id}.json`
- `POST /admin/products.json`
- `PUT /admin/products/#{product_id}.json`
- `DELETE /admin/products/#{product_id}.json`

but this breaks how `@:sub` works because we can't do a `@:sub('/products')` to hold these APIs.

Perhaps we can add something like `pathSuffix` to RemoteEndpoint? 

https://github.com/haxetink/tink_web/blob/8ba3f141bb0deff8bc348c460d50175a05fcd807/src/tink/web/proxy/Remote.hx#L17-L26

**Comment by back2dos** [comment]
If it's consistent across the board I'd be inclined to solve it via a customized client. That said, I don't mind adding it ;)

**Comment by kevinresol** [comment]
I am confused. Am I suppose to use `.sub()` manually at all? If it is intended to be internal perhaps just don't `public` it?

**Comment by back2dos** [comment]
Not sure why you would have call `.sub()` in this case (it's mostly there so that you can pass around and extend partial configurations). 

But in any case, you would directly do `{ host: ... , pathSuffix: ".json" }`, no? As I said, I don't mind it ;)

**Comment by kevinresol** [comment]
What I mean is that most problems can be solved by a custom client. I am just not sure if `.sub()` is supposed for public use.
