### ISSUE TITLE
Goto definition for @:sub

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#83]
```haxe
import tink.web.proxy.*;

class Main {
	static function main() {
		var root = new Remote<Root>(null, null);
		trace(root.foo());
		trace(root.sub().bar());
	}

}

interface Root {
	@:get
	function foo():{foo:String};
	
	@:sub
	function sub():Sub;
}

interface Sub {
	@:get
	function bar():{bar:String};
}
```

"Go to definition" works for `.foo()` but not `.sub()`.

**Comment by kevinresol** [comment]
Interestingly, reversing the two lines will make all of them work:

```haxe
trace(root.sub().bar());
trace(root.foo());
```

**Comment by kevinresol** [comment]
@gama11 Can you shed some light for me on how to debug this?

**Comment by Gama11** [comment]
Usually I just make an isolated example (without tink libs in this case I guess) and report a Haxe issue. :)

**Comment by kevinresol** [comment]
Looks like this is fixed with https://github.com/lix-pm/haxeshim/issues/34
