### ISSUE TITLE
Internal proxy

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_web#9]
Is it possible to do something like this?

```haxe
@:get('/me')
public function me(context) {
  var userId = auth.getCurrentUserId();
  return context.proxy('/users/$userId/profile');
}
```

My gut feeling is that this should not be more difficult than updating the information in the `RoutingContext` and then call `route()` once again?

**Comment by back2dos** [comment]
Sure, it wouldn't be hard at all, but isn't it kind of backward? If this is a valid route, then it must correspond to some function that you could be calling directly, in a type safe manner.

This way, you're encoding routing information about an object in a place that (apparently) doesn't have access to said object. What if you rename `users` to `user` or `profile` to `about`?

Instead, I think you should be doing something like `users.byId(userId).getProfile()` (or whatever the methods are called). If the route names change, it doesn't matter. If the underlying interfaces change, you'll get a compiler error.

Or maybe I completely misunderstand the use case here?

**Comment by kevinresol** [comment]
> This way, you're encoding routing information about an object in a place that (apparently) doesn't have access to said object.

That's true, I am in somewhere that doesn't have direct access to the "correct function". But that can be solved by dependency injection or something.
