### ISSUE TITLE
get FQDN in request

### ISSUE THREAD

**Issue by varadig** [haxetink/tink_web#93]
How to get current FQDN in request like this

@:post
function foo(query:{}){
//how to get FQDN??
}

**Comment by kevinresol** [comment]
I don't think this is a problem of tink_web...

**Comment by varadig** [comment]
its not a problem, it is a question

**Comment by varadig** [comment]
So there is not a common way, I need to use nodejs to resolve FWDN?
It is not a problem, I just looking a best practice to do that

**Comment by kevinresol** [comment]
Well yeah i don't think there are any best practice about that in tink web

**Comment by varadig** [comment]
Ok, so this is what the best I can do:
```
		this.httpServer = js.node.Http.createServer(function(request, response) {
//store somewhere
somewhere = request.headers.get("host");
		});

		this.httpServer.listen(PORT);
		this.container = new NodeContainer(this.httpServer);

```

**Comment by kevinresol** [comment]
If you decide to obtain such information in the header, you can fetch the Context object. 

```haxe
function route (ctx:Context) return ctx.request.header.ofName(HOST); 
```
