### ISSUE TITLE
Cannot stringify Void Press enter to exit...

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_web#94]
follow the documents to add this.then compile 	

       @:get
	public function search(query:{v:String}) {
		// suppose the path being routed is: `/search/?v=test`
		trace(Json.stringify(query)); // traces "test"
	}

Cannot stringify Void Press enter to exit...

haxe  rc 4.0.rc5

tink_web git version
tink_http git version

**Comment by kevinresol** [comment]
Your route has to return something

**Comment by sonygod** [comment]
thanks
