### ISSUE TITLE
php support ?

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_web#95]
Build it with: haxe -php bin -main Server -lib tink_web

follow documents,it's support  php?

https://haxetink.github.io/tink_web/#/getting-started/quick-start#Test with PHP

but compile error

  C:\HaxeToolkit\haxe\lib\tink_http/git/src/tink/http/containers/NodeContainer.hx:9: characters 18-30 : You cannot access the js package while targeting php (for js.lib.Error)

**Comment by Sanva** [comment]
I think that for PHP you should use `PHPContainer` [1], not `NodeContainer`.

You can support multiple targets using conditional compilation [2].

[1] https://github.com/haxetink/tink_http/blob/master/src/tink/http/containers/PhpContainer.hx
[2] https://haxe.org/manual/lf-condition-compilation.html

**Comment by sonygod** [comment]
@Sanva  is that support neko or hashlink?

**Comment by sonygod** [comment]
how to set port of php target?

var container =PhpContainer.inst;

**Comment by kevinresol** [comment]
PhpContainer is not a "standalone" container. 
You need a frontend server (e.g. apache/nginx) to invoke the php script

**Comment by emugel** [comment]
For dev you can just lauch a php devserver, e.g.:

`php -S localhost:8080 -t /where/is/the/path/to/serve`
