### ISSUE TITLE
Include http protocol part when defining url for remoting endpoint?

### ISSUE THREAD

**Issue by cambiata** [haxetink/tink_web#96]
The current `tink.web.proxy.Remote.hx` implementation prepends the outgoing request url with '//':
https://github.com/haxetink/tink_web/blob/c6903306c69a766468adf19c3e329ac43c6308dd/src/tink/web/proxy/Remote.hx#L58

This makes it impossible include the http protocol part in the host name when setting up a remoting endpoint. For me, this is causing problems when using remoting from a Firebase hosted app to functions driven server on the same domain:

- the hostname `mysite.firebaseapp.com` is resolved to `http://mysite...` - should be `https://mysite...`
- the hostname `https://mysite.firebaseapp.com` is resolved to `http://https://mysite...`

For now, I've hacked `tink.web.proxy.Remote.hx` to not prepend '//' to get around this.

**Comment by cambiata** [comment]
Ah, I just noticed your TODO note: 'consider putting protocol here'... :-)

**Comment by kevinresol** [comment]
You should choose the correct tink_http client, e.g. SecureJsClient

**Comment by cambiata** [comment]
Oh - lots of things to discover..! Was so proud I found JsClient..! :-)
Thanks!
